[build]
  command = "npm run build"
  publish = "client/build"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

     [[redirects]]
  force = true
  from = "/scripts/x.js"
  status = 200
  to = "http://localhost:4000/scripts/x.js"

